{
 "title": "Auth Service",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"auth_service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency(HTTP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.95,\r\n    sum(rate(auth_http_request_duration_seconds_bucket[1m])) by (le, path)\r\n)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency(gRPC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.95,\r\n    sum(rate(auth_grpc_request_duration_seconds_bucket[1m])) by (le, method)\r\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Traffic(HTTP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(auth_http_request_total[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Traffic(gRPC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(auth_grpc_request_total[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Errors/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(auth_grpc_request_total{status!=\"OK\"}[1m])) by (status)",
     "legendFormat": "gRPC_{{status}}"
    },
    {
     "expr": "sum(increase(auth_http_request_total{status=~\"4.+|5.+\"}[1m])) by (status)",
     "legendFormat": "HTTP_{{status}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(auth_grpc_request_total{status!=\"OK\"}[1m])) / sum(increase(auth_grpc_request_total[1m]))",
     "legendFormat": "gRPC"
    },
    {
     "expr": "sum(increase(auth_http_request_total{status=~\"4.+|5.+\"}[1m])) / sum(increase(auth_http_request_total[1m]))",
     "legendFormat": "HTTP"
    }
   ]
  }
 ]
}